language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"
git:
  depth: 1
branches:
  only:
  - master
services:
  - docker
before_install:
  - sudo apt-get update
  # Dependent on the version of python used, install th right miniconda dist
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
    # Useful for debugging any issues with conda
  - conda info -a
install:
  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -f environment-{$TRAVIS_PYTHON_VERSION}.yml
  - source activate test-environment
script:
  # TODO