language: python
python:
  - "3.6"
git:
  depth: 1
services:
  - docker
install:
  # First install package and it's dependencies
  # relying on setuptools to handle this during testing
  # is very inefficient
  - pip install -e .
  # Fetch the data needed for fitting
  - mkdir data && curl https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/datasets/stackloss.csv >> data/stackloss.csv
script:
  # Run tests for this package to see whether
  # changes did not break anything...
  - python setup.py test

  # FIT MODEL PHASE
  # Make some folders needed to build
  - mkdir build
  # Run package as main, this should
  # return a fitted model in ./build
  - python -m docker_deployment_example

  # Build docker container
  - docker build . -t florishoogenboom/docker_deployment_example
deploy:
  provider: script
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker push "$DOCKER_USERNAME/docker-deployment-example:latest
  on:
    branch: master
  skip_cleanup: true