name: test-env
channels:
- conda-forge
- defaults
dependencies:
- notebook=5.0.0=py36_0
- numpy=1.13.1=py36_0
- openssl=1.0.2l=vc14_0
- pandas=0.20.3=py36_0
- pip=9.0.1=py36_1
- pyqt=5.6.0=py36_2
- python=3.6.2=0
- python-dateutil=2.6.1=py36_0
- scikit-learn=0.19.0=np113py36_0
- scipy=0.19.1=np113py36_0
- setuptools=36.4.0=py36_1
- vs2015_runtime=14.0.25420=0
- wheel=0.29.0=py36_0